# Update cassandra_seeds variable if there are less than 3 seeds
# Copy configuration file to new node(s)

---

tasks:

- name: Set seeds variable
  lineinfile:
    path: ../vars/main.yml
    insertafter: "cassandra_seeds:"
    line: "  - {{ item.private_ip }}"
    state: present
  with_items:
    - "{{ ec2_dev.instances }}"
    - "{{ ec2_prod.instances }}"
  when:
    cassandra_seeds|length < 3

- name: Copy configuration file
  template:
    src: cassandra.yml.j2
    dest: "/etc/cassandra/conf/cassandra.yaml"
  become: yes
  delegate_to: "{{ item.private_ip }}"
  with_items:
    - "{{ ec2_dev.instances }}"
    - "{{ ec2_prod.instances }}"
  
  notify:
    - Restart Cassandra