# Gathers data about SG to put cluster in or creates one with default Cassandra ports + SSH (10.10.0.0/16)

---

- name: Create a security group for Cassandra accessible (SSH, Cassandra ports)
  ec2_group:
    description: Security group for Cassandra nodes
    state: present
    region: "{{ region }}"
    name: "{{ security_group }}"
    vpc_id: "{{ new_vpc.vpc.id }}"
    rules:
      - proto: tcp
        ports:
          - 22
          - 7000
          - 7001
          - 7199
          - 9042
          - 9160
          - 9142
          - 61620
          - 61621
        cidr_ip: 10.10.0.0/16