# Creates EC2 instance with configuration in ./vars/ec2dev.yml

---

- name: Create EC2 instance (dev)
  ec2:
    wait: yes
    region: "{{ region }}"
    vpc_subnet_id: "{{ new_subnet.subnet.id }}"
    group: "{{ security_group }}"

    instance_type: "{{ ec2dev_it }}"
    image: "{{ ec2dev_ami }}"
    key_name: "{{ key_name }}"
    count: "{{ ec2dev_count }}"
  register: ec2_dev